// Code generated by protoc-gen-go.
// source: server/pfs/db/persist/persist.proto
// DO NOT EDIT!

/*
Package persist is a generated protocol buffer package.

It is generated from these files:
	server/pfs/db/persist/persist.proto

It has these top-level messages:
	Append
	Clock
	ClockID
	BranchClock
	Repo
	Branch
	Diff
	Commit
*/
package persist

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "go.pedge.io/pb/go/google/protobuf"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Append struct {
	// a document only has one of these fields
	Blockrefs []string        `protobuf:"bytes,1,rep,name=blockrefs" json:"blockrefs,omitempty"`
	Children  map[string]bool `protobuf:"bytes,2,rep,name=children" json:"children,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Delete    bool            `protobuf:"varint,3,opt,name=delete" json:"delete,omitempty"`
}

func (m *Append) Reset()                    { *m = Append{} }
func (m *Append) String() string            { return proto.CompactTextString(m) }
func (*Append) ProtoMessage()               {}
func (*Append) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Append) GetChildren() map[string]bool {
	if m != nil {
		return m.Children
	}
	return nil
}

type Clock struct {
	// a document either has these two fields
	Branch string `protobuf:"bytes,1,opt,name=branch" json:"branch,omitempty"`
	Clock  uint64 `protobuf:"varint,2,opt,name=clock" json:"clock,omitempty"`
}

func (m *Clock) Reset()                    { *m = Clock{} }
func (m *Clock) String() string            { return proto.CompactTextString(m) }
func (*Clock) ProtoMessage()               {}
func (*Clock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ClockID struct {
	ID     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Repo   string `protobuf:"bytes,2,opt,name=repo" json:"repo,omitempty"`
	Branch string `protobuf:"bytes,3,opt,name=branch" json:"branch,omitempty"`
	Clock  uint64 `protobuf:"varint,4,opt,name=clock" json:"clock,omitempty"`
}

func (m *ClockID) Reset()                    { *m = ClockID{} }
func (m *ClockID) String() string            { return proto.CompactTextString(m) }
func (*ClockID) ProtoMessage()               {}
func (*ClockID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type BranchClock struct {
	Clocks []*Clock `protobuf:"bytes,1,rep,name=clocks" json:"clocks,omitempty"`
}

func (m *BranchClock) Reset()                    { *m = BranchClock{} }
func (m *BranchClock) String() string            { return proto.CompactTextString(m) }
func (*BranchClock) ProtoMessage()               {}
func (*BranchClock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BranchClock) GetClocks() []*Clock {
	if m != nil {
		return m.Clocks
	}
	return nil
}

type Repo struct {
	Name    string                     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Created *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=created" json:"created,omitempty"`
}

func (m *Repo) Reset()                    { *m = Repo{} }
func (m *Repo) String() string            { return proto.CompactTextString(m) }
func (*Repo) ProtoMessage()               {}
func (*Repo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Repo) GetCreated() *google_protobuf.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

type Branch struct {
	ID   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Repo string `protobuf:"bytes,2,opt,name=repo" json:"repo,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *Branch) Reset()                    { *m = Branch{} }
func (m *Branch) String() string            { return proto.CompactTextString(m) }
func (*Branch) ProtoMessage()               {}
func (*Branch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Diff struct {
	ID       string    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CommitID string    `protobuf:"bytes,2,opt,name=commit_id,json=commitId" json:"commit_id,omitempty"`
	Path     string    `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	Appends  []*Append `protobuf:"bytes,4,rep,name=appends" json:"appends,omitempty"`
	Size     uint64    `protobuf:"varint,5,opt,name=size" json:"size,omitempty"`
}

func (m *Diff) Reset()                    { *m = Diff{} }
func (m *Diff) String() string            { return proto.CompactTextString(m) }
func (*Diff) ProtoMessage()               {}
func (*Diff) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Diff) GetAppends() []*Append {
	if m != nil {
		return m.Appends
	}
	return nil
}

type Commit struct {
	ID           string         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Repo         string         `protobuf:"bytes,2,opt,name=repo" json:"repo,omitempty"`
	BranchClocks []*BranchClock `protobuf:"bytes,3,rep,name=branch_clocks,json=branchClocks" json:"branch_clocks,omitempty"`
	// true means append
	// false means removal
	Modifications map[string]bool            `protobuf:"bytes,4,rep,name=modifications" json:"modifications,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Started       *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=started" json:"started,omitempty"`
	Finished      *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=finished" json:"finished,omitempty"`
	Provenance    []string                   `protobuf:"bytes,7,rep,name=provenance" json:"provenance,omitempty"`
}

func (m *Commit) Reset()                    { *m = Commit{} }
func (m *Commit) String() string            { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()               {}
func (*Commit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Commit) GetBranchClocks() []*BranchClock {
	if m != nil {
		return m.BranchClocks
	}
	return nil
}

func (m *Commit) GetModifications() map[string]bool {
	if m != nil {
		return m.Modifications
	}
	return nil
}

func (m *Commit) GetStarted() *google_protobuf.Timestamp {
	if m != nil {
		return m.Started
	}
	return nil
}

func (m *Commit) GetFinished() *google_protobuf.Timestamp {
	if m != nil {
		return m.Finished
	}
	return nil
}

func init() {
	proto.RegisterType((*Append)(nil), "Append")
	proto.RegisterType((*Clock)(nil), "Clock")
	proto.RegisterType((*ClockID)(nil), "ClockID")
	proto.RegisterType((*BranchClock)(nil), "BranchClock")
	proto.RegisterType((*Repo)(nil), "Repo")
	proto.RegisterType((*Branch)(nil), "Branch")
	proto.RegisterType((*Diff)(nil), "Diff")
	proto.RegisterType((*Commit)(nil), "Commit")
}

func init() { proto.RegisterFile("server/pfs/db/persist/persist.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x53, 0xcb, 0x6e, 0x13, 0x4b,
	0x10, 0x95, 0x3d, 0xf6, 0xd8, 0x2e, 0xc7, 0x57, 0x57, 0x2d, 0x40, 0x96, 0x41, 0x10, 0x86, 0x4d,
	0x36, 0xb4, 0x15, 0xf3, 0x10, 0x82, 0x8d, 0xc1, 0x61, 0x91, 0x05, 0x12, 0x6a, 0xb1, 0x63, 0x11,
	0xcd, 0xa3, 0x26, 0x6e, 0x65, 0x5e, 0xea, 0xee, 0x58, 0x0a, 0x0b, 0x3e, 0x89, 0x7f, 0xe3, 0x0f,
	0xe8, 0xd7, 0xc4, 0x13, 0x05, 0x29, 0x61, 0x35, 0x55, 0xa7, 0xeb, 0xd4, 0xa9, 0xae, 0xd3, 0x03,
	0x2f, 0x24, 0x8a, 0x1d, 0x8a, 0x65, 0x93, 0xcb, 0x65, 0x96, 0x2c, 0x1b, 0x14, 0x92, 0x4b, 0xd5,
	0x7e, 0x69, 0x23, 0x6a, 0x55, 0x2f, 0x9e, 0x9d, 0xd7, 0xf5, 0x79, 0x81, 0x4b, 0x9b, 0x25, 0x97,
	0xf9, 0x52, 0xf1, 0x12, 0xa5, 0x8a, 0xcb, 0xc6, 0x15, 0x44, 0xbf, 0x7a, 0x10, 0x7e, 0x6c, 0x1a,
	0xac, 0x32, 0xf2, 0x04, 0x26, 0x49, 0x51, 0xa7, 0x17, 0x02, 0x73, 0x39, 0xef, 0x1d, 0x06, 0x47,
	0x13, 0xb6, 0x07, 0xc8, 0x31, 0x8c, 0xd3, 0x2d, 0x2f, 0x32, 0x81, 0xd5, 0xbc, 0xaf, 0x0f, 0xa7,
	0xab, 0x87, 0xd4, 0x11, 0xe9, 0xc6, 0xe3, 0x9f, 0x2b, 0x25, 0xae, 0xd8, 0x75, 0x19, 0x79, 0x04,
	0x61, 0x86, 0x05, 0x2a, 0x9c, 0x07, 0x87, 0xbd, 0xa3, 0x31, 0xf3, 0xd9, 0xe2, 0x03, 0xcc, 0x6e,
	0x50, 0xc8, 0xff, 0x10, 0x5c, 0xe0, 0x95, 0xd6, 0xec, 0x69, 0x4d, 0x13, 0x92, 0x07, 0x30, 0xdc,
	0xc5, 0xc5, 0x25, 0x6a, 0x29, 0xc3, 0x74, 0xc9, 0xfb, 0xfe, 0xbb, 0x5e, 0xf4, 0x06, 0x86, 0x1b,
	0x33, 0x94, 0xe9, 0x9e, 0x88, 0xb8, 0x4a, 0xb7, 0x9e, 0xe7, 0x33, 0x43, 0x4d, 0x4d, 0x81, 0xa5,
	0x0e, 0x98, 0x4b, 0xa2, 0xef, 0x30, 0xb2, 0xb4, 0xd3, 0x13, 0xf2, 0x1f, 0xf4, 0x79, 0xe6, 0x49,
	0x3a, 0x22, 0x04, 0x06, 0x02, 0x9b, 0xda, 0xd6, 0x4f, 0x98, 0x8d, 0x3b, 0xcd, 0x83, 0xbf, 0x37,
	0x1f, 0x74, 0x9b, 0xbf, 0x84, 0xe9, 0x27, 0x7b, 0xee, 0x26, 0x7b, 0x0a, 0xa1, 0xc5, 0xdd, 0x16,
	0xa7, 0xab, 0x90, 0x5a, 0x9c, 0x79, 0x34, 0xfa, 0x0a, 0x03, 0x66, 0x44, 0xb4, 0x70, 0x15, 0x97,
	0xe8, 0x47, 0xb1, 0x31, 0x79, 0x0d, 0xa3, 0x54, 0x60, 0xac, 0x30, 0xb3, 0xf3, 0x4c, 0x57, 0x0b,
	0xea, 0x2c, 0xa4, 0xad, 0x85, 0xf4, 0x5b, 0x6b, 0x21, 0x6b, 0x4b, 0xa3, 0x35, 0x84, 0x6e, 0x80,
	0x7b, 0x5d, 0xae, 0xd5, 0x0d, 0xf6, 0xba, 0xd1, 0x4f, 0x18, 0x9c, 0xf0, 0x3c, 0xbf, 0xc5, 0x7f,
	0x0c, 0x93, 0xb4, 0x2e, 0x4b, 0xae, 0xce, 0x78, 0xe6, 0x9b, 0x8c, 0x1d, 0x70, 0x6a, 0x9b, 0x37,
	0xb1, 0x6a, 0x77, 0x64, 0x63, 0xf2, 0x1c, 0x46, 0xb1, 0x7d, 0x16, 0x52, 0xef, 0xc8, 0xdc, 0x7e,
	0xe4, 0x9f, 0x09, 0x6b, 0x71, 0x43, 0x93, 0xfc, 0x07, 0xce, 0x87, 0x76, 0x87, 0x36, 0x8e, 0x7e,
	0xf7, 0x21, 0xdc, 0xd8, 0xbe, 0xf7, 0xba, 0xc2, 0x31, 0xcc, 0x9c, 0x23, 0x67, 0x7e, 0xd3, 0x81,
	0xd5, 0x3a, 0xa0, 0x1d, 0x1f, 0xd8, 0x41, 0xb2, 0x4f, 0x24, 0x59, 0xc3, 0xac, 0xac, 0x33, 0x9e,
	0xf3, 0x34, 0x56, 0xbc, 0xae, 0xda, 0xf1, 0x16, 0xd4, 0xc9, 0xd2, 0x2f, 0xdd, 0x43, 0xf7, 0x94,
	0x6f, 0x12, 0x8c, 0x37, 0x7a, 0xef, 0xc2, 0x78, 0x33, 0xbc, 0xdb, 0x1b, 0x5f, 0x4a, 0xde, 0xc2,
	0x38, 0xe7, 0x15, 0x97, 0x5b, 0x4d, 0x0b, 0xef, 0xa4, 0x5d, 0xd7, 0xea, 0x57, 0x04, 0xfa, 0x7c,
	0x87, 0x95, 0xbe, 0x03, 0xce, 0x47, 0xf6, 0x7f, 0xec, 0x20, 0x8b, 0x35, 0x90, 0xdb, 0x23, 0xff,
	0xcb, 0xaf, 0x94, 0x84, 0x56, 0xff, 0xd5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x5b, 0x77,
	0x2e, 0x4a, 0x04, 0x00, 0x00,
}
