// Code generated by protoc-gen-protolog
// source: pfs.proto
// DO NOT EDIT!

package pfs

import "go.pedge.io/protolog"

func init() {
	protolog.Register("pfs.Error", func() protolog.Message { return &Error{} })
	protolog.Register("pfs.Repository", func() protolog.Message { return &Repository{} })
	protolog.Register("pfs.Commit", func() protolog.Message { return &Commit{} })
	protolog.Register("pfs.Path", func() protolog.Message { return &Path{} })
	protolog.Register("pfs.FileInfo", func() protolog.Message { return &FileInfo{} })
	protolog.Register("pfs.Shard", func() protolog.Message { return &Shard{} })
	protolog.Register("pfs.CommitInfo", func() protolog.Message { return &CommitInfo{} })
	protolog.Register("pfs.Version", func() protolog.Message { return &Version{} })
	protolog.Register("pfs.GetVersionResponse", func() protolog.Message { return &GetVersionResponse{} })
	protolog.Register("pfs.InitRepositoryRequest", func() protolog.Message { return &InitRepositoryRequest{} })
	protolog.Register("pfs.GetFileRequest", func() protolog.Message { return &GetFileRequest{} })
	protolog.Register("pfs.GetFileInfoRequest", func() protolog.Message { return &GetFileInfoRequest{} })
	protolog.Register("pfs.GetFileInfoResponse", func() protolog.Message { return &GetFileInfoResponse{} })
	protolog.Register("pfs.MakeDirectoryRequest", func() protolog.Message { return &MakeDirectoryRequest{} })
	protolog.Register("pfs.PutFileRequest", func() protolog.Message { return &PutFileRequest{} })
	protolog.Register("pfs.ListFilesRequest", func() protolog.Message { return &ListFilesRequest{} })
	protolog.Register("pfs.ListFilesResponse", func() protolog.Message { return &ListFilesResponse{} })
	protolog.Register("pfs.BranchRequest", func() protolog.Message { return &BranchRequest{} })
	protolog.Register("pfs.BranchResponse", func() protolog.Message { return &BranchResponse{} })
	protolog.Register("pfs.CommitRequest", func() protolog.Message { return &CommitRequest{} })
	protolog.Register("pfs.GetCommitInfoRequest", func() protolog.Message { return &GetCommitInfoRequest{} })
	protolog.Register("pfs.GetCommitInfoResponse", func() protolog.Message { return &GetCommitInfoResponse{} })
	protolog.Register("pfs.ListCommitsRequest", func() protolog.Message { return &ListCommitsRequest{} })
	protolog.Register("pfs.ListCommitsResponse", func() protolog.Message { return &ListCommitsResponse{} })
	protolog.Register("pfs.PullDiffRequest", func() protolog.Message { return &PullDiffRequest{} })
	protolog.Register("pfs.PushDiffRequest", func() protolog.Message { return &PushDiffRequest{} })
}

func (m *Error) ProtologName() string {
	return "pfs.Error"
}
func (m *Repository) ProtologName() string {
	return "pfs.Repository"
}
func (m *Commit) ProtologName() string {
	return "pfs.Commit"
}
func (m *Path) ProtologName() string {
	return "pfs.Path"
}
func (m *FileInfo) ProtologName() string {
	return "pfs.FileInfo"
}
func (m *Shard) ProtologName() string {
	return "pfs.Shard"
}
func (m *CommitInfo) ProtologName() string {
	return "pfs.CommitInfo"
}
func (m *Version) ProtologName() string {
	return "pfs.Version"
}
func (m *GetVersionResponse) ProtologName() string {
	return "pfs.GetVersionResponse"
}
func (m *InitRepositoryRequest) ProtologName() string {
	return "pfs.InitRepositoryRequest"
}
func (m *GetFileRequest) ProtologName() string {
	return "pfs.GetFileRequest"
}
func (m *GetFileInfoRequest) ProtologName() string {
	return "pfs.GetFileInfoRequest"
}
func (m *GetFileInfoResponse) ProtologName() string {
	return "pfs.GetFileInfoResponse"
}
func (m *MakeDirectoryRequest) ProtologName() string {
	return "pfs.MakeDirectoryRequest"
}
func (m *PutFileRequest) ProtologName() string {
	return "pfs.PutFileRequest"
}
func (m *ListFilesRequest) ProtologName() string {
	return "pfs.ListFilesRequest"
}
func (m *ListFilesResponse) ProtologName() string {
	return "pfs.ListFilesResponse"
}
func (m *BranchRequest) ProtologName() string {
	return "pfs.BranchRequest"
}
func (m *BranchResponse) ProtologName() string {
	return "pfs.BranchResponse"
}
func (m *CommitRequest) ProtologName() string {
	return "pfs.CommitRequest"
}
func (m *GetCommitInfoRequest) ProtologName() string {
	return "pfs.GetCommitInfoRequest"
}
func (m *GetCommitInfoResponse) ProtologName() string {
	return "pfs.GetCommitInfoResponse"
}
func (m *ListCommitsRequest) ProtologName() string {
	return "pfs.ListCommitsRequest"
}
func (m *ListCommitsResponse) ProtologName() string {
	return "pfs.ListCommitsResponse"
}
func (m *PullDiffRequest) ProtologName() string {
	return "pfs.PullDiffRequest"
}
func (m *PushDiffRequest) ProtologName() string {
	return "pfs.PushDiffRequest"
}
