FROM alpine:3.10

MAINTAINER jdoliner@pachyerm.io

LABEL name="Pachyderm" \
      vendor="Pachyderm"

RUN apk -U add ca-certificates

COPY LICENSE /licenses
COPY pachd /pachd
COPY dex-assets /dex-assets

ENTRYPOINT ["/pachd"]
