FROM ubuntu:14.04
MAINTAINER jdoliner@pachyderm.io

RUN \
  apt-get update -yq && \
  apt-get install -yq --no-install-recommends \
    ca-certificates \
    fuse \
    wget && \
  apt-get clean && \
  rm -rf /var/lib/apt
ADD ./job-shim /
