FROM ubuntu:14.04
MAINTAINER jdoliner@pachyderm.io

VOLUME ["/pfs"]
RUN \
  apt-get update -yq && \
  apt-get install -yq --no-install-recommends \
    btrfs-tools \
    ca-certificates \
    fuse && \
  apt-get clean && \
  rm -rf /var/lib/apt
ADD _tmp/pfs /bin/pfs
ENTRYPOINT ["/bin/pfs", "mount"]
