FROM ubuntu:14.04
MAINTAINER peter@pachyderm.io

RUN \
  apt-get update -yq && \
  apt-get install -yq --no-install-recommends \
    fuse \
    ca-certificates && \
  apt-get clean && \
  rm -rf /var/lib/apt
ADD _tmp/pfsmount /
ENTRYPOINT ["/pfsmount"]
