FROM python:3.7 as mkdocs
RUN apt-get clean && apt-get update 

WORKDIR /usr/src/app/doc
COPY doc/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get install -y mkdocs

COPY . /usr/src/app/
RUN ./build.sh


FROM mkdocs as netlify

RUN apt-get install -y npm
RUN npm install netlify-cli -g
# RUN npm install netlify-plugin-checklinks



