FROM ubuntu:14.04
MAINTAINER jdoliner@pachyderm.io

RUN \
  apt-get update -yq && \
  apt-get install -yq --no-install-recommends \
    ca-certificates && \
  apt-get clean && \
  rm -rf /var/lib/apt
ADD _tmp/pachd /pachd
ENV PACH_BUILD_NUMBER %%PACH_BUILD_NUMBER%%
ENTRYPOINT ["/pachd"]
