FROM ubuntu:14.04
MAINTAINER jdoliner@pachyderm.io

RUN \
  apt-get update -yq && \
  apt-get install -yq --no-install-recommends \
    ca-certificates \
    fuse && \
  apt-get clean && \
  rm -rf /var/lib/apt
ADD _tmp/pfsd /
ENTRYPOINT ["/pfsd"]
