# syntax=docker/dockerfile:1.0-experimental
ARG GO_VERSION
FROM golang:${GO_VERSION}
RUN apt update && apt install ca-certificates
WORKDIR /app
COPY . .
ARG LD_FLAGS
# NOTE: CGO explicitly enabled on `pachctl` build so we can benefit from glibc
# patches
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go install -ldflags "${LD_FLAGS}" -gcflags "${GC_FLAGS}" ./src/server/cmd/pachctl
