FROM python:3

WORKDIR /usr/src/app/doc
COPY doc/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update 
RUN apt-get install -y mkdocs
RUN apt-get install -y npm
RUN npm install netlify-cli -g

COPY . /usr/src/app/

RUN ./build.sh
