FROM busybox
MAINTAINER peter@pachyderm.io

RUN mkdir -p /etc/ssl/certs
ADD etc/certs/ca-certificates.crt /etc/ssl/certs/
COPY etc/bin/btrfs-wrapper /bin/btrfs
ADD _tmp/pfsd/pfsd /bin/pfsd
ENTRYPOINT ["/bin/pfsd"]
