#!/bin/sh
set -e
H="Metadata-Flavor: Google"
project="$(curl -s -H "$H" http://metadata/computeMetadata/v1/project/project-id)"
zone="$(curl -s -H "$H" http://metadata/computeMetadata/v1/instance/zone |
cut -d/ -f4)"
disk="$(curl -s -H "$H" http://metadata/computeMetadata/v1/instance/hostname |
cut -d. -f1)"

gcloud \
    compute \
        --project "$project" \
    disks snapshot "$disk" \
        --zone "$zone" \
        --snapshot-names "snapshot-$(date +%Y-%m-%d)"
