FROM ubuntu:20.04
# Fix timezone issue
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN useradd -ms /bin/bash test
ENTRYPOINT ["cp", "/pfs/in/file", "/pfs/out/file"]
