// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: server/worker/datum/datum.proto

package datum

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	pfs "github.com/pachyderm/pachyderm/v2/src/pfs"
	pps "github.com/pachyderm/pachyderm/v2/src/pps"
	common "github.com/pachyderm/pachyderm/v2/src/server/worker/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type State int32

const (
	State_PROCESSED State = 0
	State_FAILED    State = 1
	State_RECOVERED State = 2
)

var State_name = map[int32]string{
	0: "PROCESSED",
	1: "FAILED",
	2: "RECOVERED",
}

var State_value = map[string]int32{
	"PROCESSED": 0,
	"FAILED":    1,
	"RECOVERED": 2,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_96ec7427544ac634, []int{0}
}

type KeyTask_Type int32

const (
	KeyTask_JOIN  KeyTask_Type = 0
	KeyTask_GROUP KeyTask_Type = 1
)

var KeyTask_Type_name = map[int32]string{
	0: "JOIN",
	1: "GROUP",
}

var KeyTask_Type_value = map[string]int32{
	"JOIN":  0,
	"GROUP": 1,
}

func (x KeyTask_Type) String() string {
	return proto.EnumName(KeyTask_Type_name, int32(x))
}

func (KeyTask_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_96ec7427544ac634, []int{6, 0}
}

type MergeTask_Type int32

const (
	MergeTask_JOIN  MergeTask_Type = 0
	MergeTask_GROUP MergeTask_Type = 1
)

var MergeTask_Type_name = map[int32]string{
	0: "JOIN",
	1: "GROUP",
}

var MergeTask_Type_value = map[string]int32{
	"JOIN":  0,
	"GROUP": 1,
}

func (x MergeTask_Type) String() string {
	return proto.EnumName(MergeTask_Type_name, int32(x))
}

func (MergeTask_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_96ec7427544ac634, []int{8, 0}
}

type Meta struct {
	Job                  *pps.Job          `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Inputs               []*common.Input   `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Hash                 string            `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	State                State             `protobuf:"varint,4,opt,name=state,proto3,enum=datum.State" json:"state,omitempty"`
	Reason               string            `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Stats                *pps.ProcessStats `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats,omitempty"`
	Index                int64             `protobuf:"varint,7,opt,name=index,proto3" json:"index,omitempty"`
	ImageId              string            `protobuf:"bytes,8,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ec7427544ac634, []int{0}
}
func (m *Meta) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return m.Size()
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetJob() *pps.Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *Meta) GetInputs() []*common.Input {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Meta) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Meta) GetState() State {
	if m != nil {
		return m.State
	}
	return State_PROCESSED
}

func (m *Meta) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Meta) GetStats() *pps.ProcessStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *Meta) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Meta) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

type Stats struct {
	ProcessStats         *pps.ProcessStats `protobuf:"bytes,1,opt,name=process_stats,json=processStats,proto3" json:"process_stats,omitempty"`
	Processed            int64             `protobuf:"varint,2,opt,name=processed,proto3" json:"processed,omitempty"`
	Skipped              int64             `protobuf:"varint,3,opt,name=skipped,proto3" json:"skipped,omitempty"`
	Total                int64             `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Failed               int64             `protobuf:"varint,5,opt,name=failed,proto3" json:"failed,omitempty"`
	Recovered            int64             `protobuf:"varint,6,opt,name=recovered,proto3" json:"recovered,omitempty"`
	FailedId             string            `protobuf:"bytes,7,opt,name=failed_id,json=failedId,proto3" json:"failed_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ec7427544ac634, []int{1}
}
func (m *Stats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(m, src)
}
func (m *Stats) XXX_Size() int {
	return m.Size()
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetProcessStats() *pps.ProcessStats {
	if m != nil {
		return m.ProcessStats
	}
	return nil
}

func (m *Stats) GetProcessed() int64 {
	if m != nil {
		return m.Processed
	}
	return 0
}

func (m *Stats) GetSkipped() int64 {
	if m != nil {
		return m.Skipped
	}
	return 0
}

func (m *Stats) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Stats) GetFailed() int64 {
	if m != nil {
		return m.Failed
	}
	return 0
}

func (m *Stats) GetRecovered() int64 {
	if m != nil {
		return m.Recovered
	}
	return 0
}

func (m *Stats) GetFailedId() string {
	if m != nil {
		return m.FailedId
	}
	return ""
}

type PFSTask struct {
	Input                *pps.PFSInput  `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	PathRange            *pfs.PathRange `protobuf:"bytes,2,opt,name=path_range,json=pathRange,proto3" json:"path_range,omitempty"`
	BaseIndex            int64          `protobuf:"varint,3,opt,name=base_index,json=baseIndex,proto3" json:"base_index,omitempty"`
	AuthToken            string         `protobuf:"bytes,4,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PFSTask) Reset()         { *m = PFSTask{} }
func (m *PFSTask) String() string { return proto.CompactTextString(m) }
func (*PFSTask) ProtoMessage()    {}
func (*PFSTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ec7427544ac634, []int{2}
}
func (m *PFSTask) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PFSTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PFSTask.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PFSTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PFSTask.Merge(m, src)
}
func (m *PFSTask) XXX_Size() int {
	return m.Size()
}
func (m *PFSTask) XXX_DiscardUnknown() {
	xxx_messageInfo_PFSTask.DiscardUnknown(m)
}

var xxx_messageInfo_PFSTask proto.InternalMessageInfo

func (m *PFSTask) GetInput() *pps.PFSInput {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *PFSTask) GetPathRange() *pfs.PathRange {
	if m != nil {
		return m.PathRange
	}
	return nil
}

func (m *PFSTask) GetBaseIndex() int64 {
	if m != nil {
		return m.BaseIndex
	}
	return 0
}

func (m *PFSTask) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type PFSTaskResult struct {
	FileSetId            string   `protobuf:"bytes,1,opt,name=file_set_id,json=fileSetId,proto3" json:"file_set_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PFSTaskResult) Reset()         { *m = PFSTaskResult{} }
func (m *PFSTaskResult) String() string { return proto.CompactTextString(m) }
func (*PFSTaskResult) ProtoMessage()    {}
func (*PFSTaskResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ec7427544ac634, []int{3}
}
func (m *PFSTaskResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PFSTaskResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PFSTaskResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PFSTaskResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PFSTaskResult.Merge(m, src)
}
func (m *PFSTaskResult) XXX_Size() int {
	return m.Size()
}
func (m *PFSTaskResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PFSTaskResult.DiscardUnknown(m)
}

var xxx_messageInfo_PFSTaskResult proto.InternalMessageInfo

func (m *PFSTaskResult) GetFileSetId() string {
	if m != nil {
		return m.FileSetId
	}
	return ""
}

type CrossTask struct {
	FileSetIds           []string       `protobuf:"bytes,1,rep,name=file_set_ids,json=fileSetIds,proto3" json:"file_set_ids,omitempty"`
	BaseFileSetIndex     int64          `protobuf:"varint,2,opt,name=base_file_set_index,json=baseFileSetIndex,proto3" json:"base_file_set_index,omitempty"`
	BaseFileSetPathRange *pfs.PathRange `protobuf:"bytes,3,opt,name=base_file_set_path_range,json=baseFileSetPathRange,proto3" json:"base_file_set_path_range,omitempty"`
	BaseIndex            int64          `protobuf:"varint,4,opt,name=base_index,json=baseIndex,proto3" json:"base_index,omitempty"`
	AuthToken            string         `protobuf:"bytes,5,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CrossTask) Reset()         { *m = CrossTask{} }
func (m *CrossTask) String() string { return proto.CompactTextString(m) }
func (*CrossTask) ProtoMessage()    {}
func (*CrossTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ec7427544ac634, []int{4}
}
func (m *CrossTask) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CrossTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CrossTask.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CrossTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossTask.Merge(m, src)
}
func (m *CrossTask) XXX_Size() int {
	return m.Size()
}
func (m *CrossTask) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossTask.DiscardUnknown(m)
}

var xxx_messageInfo_CrossTask proto.InternalMessageInfo

func (m *CrossTask) GetFileSetIds() []string {
	if m != nil {
		return m.FileSetIds
	}
	return nil
}

func (m *CrossTask) GetBaseFileSetIndex() int64 {
	if m != nil {
		return m.BaseFileSetIndex
	}
	return 0
}

func (m *CrossTask) GetBaseFileSetPathRange() *pfs.PathRange {
	if m != nil {
		return m.BaseFileSetPathRange
	}
	return nil
}

func (m *CrossTask) GetBaseIndex() int64 {
	if m != nil {
		return m.BaseIndex
	}
	return 0
}

func (m *CrossTask) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type CrossTaskResult struct {
	FileSetId            string   `protobuf:"bytes,1,opt,name=file_set_id,json=fileSetId,proto3" json:"file_set_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrossTaskResult) Reset()         { *m = CrossTaskResult{} }
func (m *CrossTaskResult) String() string { return proto.CompactTextString(m) }
func (*CrossTaskResult) ProtoMessage()    {}
func (*CrossTaskResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ec7427544ac634, []int{5}
}
func (m *CrossTaskResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CrossTaskResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CrossTaskResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CrossTaskResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossTaskResult.Merge(m, src)
}
func (m *CrossTaskResult) XXX_Size() int {
	return m.Size()
}
func (m *CrossTaskResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossTaskResult.DiscardUnknown(m)
}

var xxx_messageInfo_CrossTaskResult proto.InternalMessageInfo

func (m *CrossTaskResult) GetFileSetId() string {
	if m != nil {
		return m.FileSetId
	}
	return ""
}

type KeyTask struct {
	FileSetId            string         `protobuf:"bytes,1,opt,name=file_set_id,json=fileSetId,proto3" json:"file_set_id,omitempty"`
	PathRange            *pfs.PathRange `protobuf:"bytes,2,opt,name=path_range,json=pathRange,proto3" json:"path_range,omitempty"`
	Type                 KeyTask_Type   `protobuf:"varint,3,opt,name=type,proto3,enum=datum.KeyTask_Type" json:"type,omitempty"`
	AuthToken            string         `protobuf:"bytes,4,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *KeyTask) Reset()         { *m = KeyTask{} }
func (m *KeyTask) String() string { return proto.CompactTextString(m) }
func (*KeyTask) ProtoMessage()    {}
func (*KeyTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ec7427544ac634, []int{6}
}
func (m *KeyTask) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeyTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeyTask.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeyTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyTask.Merge(m, src)
}
func (m *KeyTask) XXX_Size() int {
	return m.Size()
}
func (m *KeyTask) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyTask.DiscardUnknown(m)
}

var xxx_messageInfo_KeyTask proto.InternalMessageInfo

func (m *KeyTask) GetFileSetId() string {
	if m != nil {
		return m.FileSetId
	}
	return ""
}

func (m *KeyTask) GetPathRange() *pfs.PathRange {
	if m != nil {
		return m.PathRange
	}
	return nil
}

func (m *KeyTask) GetType() KeyTask_Type {
	if m != nil {
		return m.Type
	}
	return KeyTask_JOIN
}

func (m *KeyTask) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type KeyTaskResult struct {
	FileSetId            string   `protobuf:"bytes,1,opt,name=file_set_id,json=fileSetId,proto3" json:"file_set_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyTaskResult) Reset()         { *m = KeyTaskResult{} }
func (m *KeyTaskResult) String() string { return proto.CompactTextString(m) }
func (*KeyTaskResult) ProtoMessage()    {}
func (*KeyTaskResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ec7427544ac634, []int{7}
}
func (m *KeyTaskResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeyTaskResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeyTaskResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeyTaskResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyTaskResult.Merge(m, src)
}
func (m *KeyTaskResult) XXX_Size() int {
	return m.Size()
}
func (m *KeyTaskResult) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyTaskResult.DiscardUnknown(m)
}

var xxx_messageInfo_KeyTaskResult proto.InternalMessageInfo

func (m *KeyTaskResult) GetFileSetId() string {
	if m != nil {
		return m.FileSetId
	}
	return ""
}

type MergeTask struct {
	FileSetIds           []string       `protobuf:"bytes,1,rep,name=file_set_ids,json=fileSetIds,proto3" json:"file_set_ids,omitempty"`
	PathRange            *pfs.PathRange `protobuf:"bytes,2,opt,name=path_range,json=pathRange,proto3" json:"path_range,omitempty"`
	Type                 MergeTask_Type `protobuf:"varint,3,opt,name=type,proto3,enum=datum.MergeTask_Type" json:"type,omitempty"`
	AuthToken            string         `protobuf:"bytes,4,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MergeTask) Reset()         { *m = MergeTask{} }
func (m *MergeTask) String() string { return proto.CompactTextString(m) }
func (*MergeTask) ProtoMessage()    {}
func (*MergeTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ec7427544ac634, []int{8}
}
func (m *MergeTask) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MergeTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MergeTask.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MergeTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MergeTask.Merge(m, src)
}
func (m *MergeTask) XXX_Size() int {
	return m.Size()
}
func (m *MergeTask) XXX_DiscardUnknown() {
	xxx_messageInfo_MergeTask.DiscardUnknown(m)
}

var xxx_messageInfo_MergeTask proto.InternalMessageInfo

func (m *MergeTask) GetFileSetIds() []string {
	if m != nil {
		return m.FileSetIds
	}
	return nil
}

func (m *MergeTask) GetPathRange() *pfs.PathRange {
	if m != nil {
		return m.PathRange
	}
	return nil
}

func (m *MergeTask) GetType() MergeTask_Type {
	if m != nil {
		return m.Type
	}
	return MergeTask_JOIN
}

func (m *MergeTask) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type MergeTaskResult struct {
	FileSetId            string   `protobuf:"bytes,1,opt,name=file_set_id,json=fileSetId,proto3" json:"file_set_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MergeTaskResult) Reset()         { *m = MergeTaskResult{} }
func (m *MergeTaskResult) String() string { return proto.CompactTextString(m) }
func (*MergeTaskResult) ProtoMessage()    {}
func (*MergeTaskResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ec7427544ac634, []int{9}
}
func (m *MergeTaskResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MergeTaskResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MergeTaskResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MergeTaskResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MergeTaskResult.Merge(m, src)
}
func (m *MergeTaskResult) XXX_Size() int {
	return m.Size()
}
func (m *MergeTaskResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MergeTaskResult.DiscardUnknown(m)
}

var xxx_messageInfo_MergeTaskResult proto.InternalMessageInfo

func (m *MergeTaskResult) GetFileSetId() string {
	if m != nil {
		return m.FileSetId
	}
	return ""
}

type ComposeTask struct {
	FileSetIds           []string `protobuf:"bytes,1,rep,name=file_set_ids,json=fileSetIds,proto3" json:"file_set_ids,omitempty"`
	AuthToken            string   `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComposeTask) Reset()         { *m = ComposeTask{} }
func (m *ComposeTask) String() string { return proto.CompactTextString(m) }
func (*ComposeTask) ProtoMessage()    {}
func (*ComposeTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ec7427544ac634, []int{10}
}
func (m *ComposeTask) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ComposeTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ComposeTask.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ComposeTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComposeTask.Merge(m, src)
}
func (m *ComposeTask) XXX_Size() int {
	return m.Size()
}
func (m *ComposeTask) XXX_DiscardUnknown() {
	xxx_messageInfo_ComposeTask.DiscardUnknown(m)
}

var xxx_messageInfo_ComposeTask proto.InternalMessageInfo

func (m *ComposeTask) GetFileSetIds() []string {
	if m != nil {
		return m.FileSetIds
	}
	return nil
}

func (m *ComposeTask) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type ComposeTaskResult struct {
	FileSetId            string   `protobuf:"bytes,1,opt,name=file_set_id,json=fileSetId,proto3" json:"file_set_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComposeTaskResult) Reset()         { *m = ComposeTaskResult{} }
func (m *ComposeTaskResult) String() string { return proto.CompactTextString(m) }
func (*ComposeTaskResult) ProtoMessage()    {}
func (*ComposeTaskResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ec7427544ac634, []int{11}
}
func (m *ComposeTaskResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ComposeTaskResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ComposeTaskResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ComposeTaskResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComposeTaskResult.Merge(m, src)
}
func (m *ComposeTaskResult) XXX_Size() int {
	return m.Size()
}
func (m *ComposeTaskResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ComposeTaskResult.DiscardUnknown(m)
}

var xxx_messageInfo_ComposeTaskResult proto.InternalMessageInfo

func (m *ComposeTaskResult) GetFileSetId() string {
	if m != nil {
		return m.FileSetId
	}
	return ""
}

type SetSpec struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	SizeBytes            int64    `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSpec) Reset()         { *m = SetSpec{} }
func (m *SetSpec) String() string { return proto.CompactTextString(m) }
func (*SetSpec) ProtoMessage()    {}
func (*SetSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ec7427544ac634, []int{12}
}
func (m *SetSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetSpec.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SetSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSpec.Merge(m, src)
}
func (m *SetSpec) XXX_Size() int {
	return m.Size()
}
func (m *SetSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSpec.DiscardUnknown(m)
}

var xxx_messageInfo_SetSpec proto.InternalMessageInfo

func (m *SetSpec) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *SetSpec) GetSizeBytes() int64 {
	if m != nil {
		return m.SizeBytes
	}
	return 0
}

func init() {
	proto.RegisterEnum("datum.State", State_name, State_value)
	proto.RegisterEnum("datum.KeyTask_Type", KeyTask_Type_name, KeyTask_Type_value)
	proto.RegisterEnum("datum.MergeTask_Type", MergeTask_Type_name, MergeTask_Type_value)
	proto.RegisterType((*Meta)(nil), "datum.Meta")
	proto.RegisterType((*Stats)(nil), "datum.Stats")
	proto.RegisterType((*PFSTask)(nil), "datum.PFSTask")
	proto.RegisterType((*PFSTaskResult)(nil), "datum.PFSTaskResult")
	proto.RegisterType((*CrossTask)(nil), "datum.CrossTask")
	proto.RegisterType((*CrossTaskResult)(nil), "datum.CrossTaskResult")
	proto.RegisterType((*KeyTask)(nil), "datum.KeyTask")
	proto.RegisterType((*KeyTaskResult)(nil), "datum.KeyTaskResult")
	proto.RegisterType((*MergeTask)(nil), "datum.MergeTask")
	proto.RegisterType((*MergeTaskResult)(nil), "datum.MergeTaskResult")
	proto.RegisterType((*ComposeTask)(nil), "datum.ComposeTask")
	proto.RegisterType((*ComposeTaskResult)(nil), "datum.ComposeTaskResult")
	proto.RegisterType((*SetSpec)(nil), "datum.SetSpec")
}

func init() { proto.RegisterFile("server/worker/datum/datum.proto", fileDescriptor_96ec7427544ac634) }

var fileDescriptor_96ec7427544ac634 = []byte{
	// 814 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x92, 0xdb, 0x44,
	0x10, 0xce, 0xac, 0xfc, 0xa7, 0xf6, 0x3a, 0x71, 0x26, 0x0b, 0x25, 0x12, 0xd6, 0x18, 0x57, 0x01,
	0x26, 0x55, 0x58, 0xac, 0x73, 0xca, 0x0d, 0xe2, 0xb5, 0x53, 0x0a, 0x24, 0x76, 0x8d, 0x16, 0x0e,
	0x5c, 0x54, 0xb2, 0xd5, 0xb6, 0x85, 0x7f, 0x34, 0xa5, 0x19, 0x1b, 0xcc, 0xdb, 0xf0, 0x26, 0x9c,
	0x28, 0x8e, 0x3c, 0x02, 0xb5, 0x14, 0x0f, 0xc1, 0x8d, 0x9a, 0x19, 0xd9, 0x6b, 0xa7, 0x48, 0x62,
	0xa8, 0x5c, 0x76, 0xd5, 0x5f, 0x7f, 0xea, 0xee, 0xef, 0x6b, 0x79, 0x06, 0x3e, 0x10, 0x98, 0xae,
	0x31, 0x75, 0x7f, 0x48, 0xd2, 0x19, 0xa6, 0x6e, 0x14, 0xca, 0xd5, 0xc2, 0xfc, 0x6d, 0xf1, 0x34,
	0x91, 0x09, 0xcd, 0xeb, 0xe0, 0x7e, 0x85, 0x8f, 0x85, 0xcb, 0xc7, 0xc2, 0xa0, 0xf7, 0x2b, 0x9c,
	0x0b, 0x97, 0xf3, 0x6d, 0xf8, 0xe1, 0x61, 0x95, 0x51, 0xb2, 0x58, 0x24, 0xcb, 0xec, 0x9f, 0xa1,
	0x34, 0xfe, 0x26, 0x90, 0x7b, 0x8e, 0x32, 0xa4, 0xe7, 0x60, 0x7d, 0x9f, 0x0c, 0x1d, 0x52, 0x27,
	0xcd, 0x72, 0xbb, 0xdc, 0xe2, 0x5c, 0x04, 0xeb, 0x76, 0xeb, 0x59, 0x32, 0x64, 0x0a, 0xa7, 0x1f,
	0x41, 0x21, 0x5e, 0xf2, 0x95, 0x14, 0xce, 0x49, 0xdd, 0x6a, 0x96, 0xdb, 0x95, 0x56, 0x56, 0xc6,
	0x53, 0x28, 0xcb, 0x92, 0x94, 0x42, 0x6e, 0x1a, 0x8a, 0xa9, 0x63, 0xd5, 0x49, 0xd3, 0x66, 0xfa,
	0x99, 0x36, 0x20, 0x2f, 0x64, 0x28, 0xd1, 0xc9, 0xd5, 0x49, 0xf3, 0x76, 0xfb, 0xb4, 0x65, 0x74,
	0xf8, 0x0a, 0x63, 0x26, 0x45, 0xdf, 0x85, 0x42, 0x8a, 0xa1, 0x48, 0x96, 0x4e, 0x5e, 0xbf, 0x99,
	0x45, 0xf4, 0xa1, 0x79, 0x57, 0x38, 0x05, 0x3d, 0xd7, 0xd9, 0x76, 0xae, 0x41, 0x9a, 0x8c, 0x50,
	0x08, 0x55, 0x43, 0x98, 0x1a, 0x82, 0x9e, 0x41, 0x3e, 0x5e, 0x46, 0xf8, 0xa3, 0x53, 0xac, 0x93,
	0xa6, 0xc5, 0x4c, 0x40, 0xdf, 0x83, 0x52, 0xbc, 0x08, 0x27, 0x18, 0xc4, 0x91, 0x53, 0xd2, 0xb5,
	0x8b, 0x3a, 0xf6, 0xa2, 0xc6, 0x9f, 0x04, 0xf2, 0xba, 0x02, 0x7d, 0x0c, 0x15, 0x6e, 0x2a, 0x06,
	0xa6, 0x1d, 0x79, 0x4d, 0xbb, 0x53, 0xbe, 0x17, 0xd1, 0xf7, 0xc1, 0xce, 0x62, 0x8c, 0x9c, 0x13,
	0xdd, 0xf9, 0x06, 0xa0, 0x0e, 0x14, 0xc5, 0x2c, 0xe6, 0x1c, 0x23, 0x6d, 0x89, 0xc5, 0xb6, 0xa1,
	0x9a, 0x56, 0x26, 0x32, 0x9c, 0x6b, 0x57, 0x2c, 0x66, 0x02, 0xe5, 0xc3, 0x38, 0x8c, 0xe7, 0x18,
	0x69, 0x1f, 0x2c, 0x96, 0x45, 0xaa, 0x4b, 0x8a, 0xa3, 0x64, 0x8d, 0x29, 0x46, 0xda, 0x0b, 0x8b,
	0xdd, 0x00, 0xf4, 0x01, 0xd8, 0x86, 0xa7, 0x44, 0x16, 0xb5, 0xc8, 0x92, 0x01, 0xbc, 0xa8, 0xf1,
	0x33, 0x81, 0xe2, 0xa0, 0xe7, 0x5f, 0x85, 0x62, 0x46, 0x3f, 0x56, 0x16, 0xf1, 0x95, 0xcc, 0xf4,
	0x55, 0x77, 0xfa, 0x7a, 0xbe, 0xd9, 0xa3, 0x49, 0xd3, 0xcf, 0x01, 0x78, 0x28, 0xa7, 0x41, 0x1a,
	0x2e, 0x27, 0xa8, 0x55, 0x95, 0xdb, 0x77, 0x5b, 0x7c, 0x6c, 0xc8, 0xa1, 0x9c, 0x32, 0x95, 0x60,
	0x36, 0xdf, 0x3e, 0xd2, 0x73, 0x80, 0x61, 0x28, 0x30, 0x30, 0x1b, 0x30, 0x5a, 0x6d, 0x85, 0x78,
	0x7a, 0x0b, 0xe7, 0x00, 0xe1, 0x4a, 0x4e, 0x03, 0x99, 0xcc, 0x70, 0xa9, 0x25, 0xdb, 0xcc, 0x56,
	0xc8, 0x95, 0x02, 0x1a, 0x2e, 0x54, 0xb2, 0x11, 0x19, 0x8a, 0xd5, 0x5c, 0xd2, 0x1a, 0x94, 0xc7,
	0xf1, 0x1c, 0x03, 0x81, 0x52, 0x69, 0x22, 0xe6, 0x05, 0x05, 0xf9, 0x28, 0xbd, 0xa8, 0xf1, 0x17,
	0x01, 0xbb, 0x93, 0x26, 0x42, 0x68, 0x59, 0x75, 0x38, 0xdd, 0x63, 0xab, 0xed, 0x59, 0x4d, 0x9b,
	0xc1, 0x8e, 0x2e, 0xe8, 0x67, 0x70, 0x4f, 0x8f, 0x77, 0x43, 0xd3, 0x73, 0x9a, 0x7d, 0x55, 0x55,
	0xaa, 0x97, 0x91, 0xf5, 0xb8, 0x1e, 0x38, 0x87, 0xf4, 0x3d, 0x37, 0xac, 0x57, 0xb9, 0x71, 0xb6,
	0x57, 0x66, 0xf0, 0x0a, 0x63, 0x72, 0xaf, 0x37, 0x26, 0xff, 0xb2, 0x31, 0x17, 0x70, 0x67, 0x27,
	0xf3, 0x48, 0x6b, 0x7e, 0x21, 0x50, 0xfc, 0x0a, 0x37, 0xda, 0x98, 0x37, 0x70, 0xff, 0xc7, 0x9e,
	0x3f, 0x81, 0x9c, 0xdc, 0x70, 0xe3, 0xc2, 0xed, 0xf6, 0xbd, 0xec, 0xb7, 0x9c, 0xf5, 0x6b, 0x5d,
	0x6d, 0x38, 0x32, 0x4d, 0x78, 0xd3, 0xc6, 0x1f, 0x40, 0x4e, 0x91, 0x69, 0x09, 0x72, 0xcf, 0xfa,
	0xde, 0x8b, 0xea, 0x2d, 0x6a, 0x43, 0xfe, 0x29, 0xeb, 0x7f, 0x33, 0xa8, 0x12, 0xf5, 0x39, 0x64,
	0x15, 0x8f, 0xd4, 0xfc, 0x2b, 0x01, 0xfb, 0x39, 0xa6, 0x13, 0x3c, 0xf2, 0x73, 0xf8, 0xef, 0xba,
	0x3f, 0x3d, 0xd0, 0xfd, 0x4e, 0xa6, 0x7b, 0xd7, 0xf3, 0x6d, 0x29, 0xbf, 0x80, 0x3b, 0xbb, 0x9a,
	0x47, 0x6a, 0x7f, 0x01, 0xe5, 0x4e, 0xb2, 0xe0, 0x89, 0x38, 0x56, 0xfc, 0xe1, 0x7c, 0x27, 0x2f,
	0xcf, 0xf7, 0x08, 0xee, 0xee, 0xd5, 0x3b, 0x72, 0x88, 0x2f, 0xa0, 0xe8, 0xa3, 0xf4, 0x39, 0x8e,
	0xd4, 0x11, 0xb6, 0x5c, 0x2d, 0x86, 0x98, 0x6a, 0x96, 0xc5, 0xb2, 0x48, 0xb5, 0x15, 0xf1, 0x4f,
	0x18, 0x0c, 0x37, 0x12, 0xc5, 0xf6, 0xa4, 0x54, 0xc8, 0x13, 0x05, 0x3c, 0xbc, 0x30, 0x67, 0x31,
	0xd2, 0x0a, 0xd8, 0x03, 0xd6, 0xef, 0x74, 0x7d, 0xbf, 0x7b, 0x59, 0xbd, 0x45, 0x01, 0x0a, 0xbd,
	0x2f, 0xbd, 0xaf, 0xbb, 0x97, 0x55, 0xa2, 0x52, 0xac, 0xdb, 0xe9, 0x7f, 0xdb, 0x65, 0xdd, 0xcb,
	0xea, 0xc9, 0x93, 0xa7, 0xbf, 0x5d, 0xd7, 0xc8, 0xef, 0xd7, 0x35, 0xf2, 0xc7, 0x75, 0x8d, 0x7c,
	0xf7, 0x78, 0x12, 0xcb, 0xe9, 0x6a, 0xa8, 0xee, 0x25, 0x97, 0x87, 0xa3, 0xe9, 0x26, 0xc2, 0x74,
	0xff, 0x69, 0xdd, 0x76, 0x45, 0x3a, 0x72, 0xff, 0xe5, 0x62, 0x1d, 0x16, 0xf4, 0x5d, 0xf8, 0xe8,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x61, 0x5c, 0xf5, 0x06, 0x76, 0x07, 0x00, 0x00,
}

func (m *Meta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Meta) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Meta) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ImageId) > 0 {
		i -= len(m.ImageId)
		copy(dAtA[i:], m.ImageId)
		i = encodeVarintDatum(dAtA, i, uint64(len(m.ImageId)))
		i--
		dAtA[i] = 0x42
	}
	if m.Index != 0 {
		i = encodeVarintDatum(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x38
	}
	if m.Stats != nil {
		{
			size, err := m.Stats.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDatum(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintDatum(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x2a
	}
	if m.State != 0 {
		i = encodeVarintDatum(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintDatum(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Inputs) > 0 {
		for iNdEx := len(m.Inputs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Inputs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDatum(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Job != nil {
		{
			size, err := m.Job.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDatum(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Stats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Stats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Stats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.FailedId) > 0 {
		i -= len(m.FailedId)
		copy(dAtA[i:], m.FailedId)
		i = encodeVarintDatum(dAtA, i, uint64(len(m.FailedId)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Recovered != 0 {
		i = encodeVarintDatum(dAtA, i, uint64(m.Recovered))
		i--
		dAtA[i] = 0x30
	}
	if m.Failed != 0 {
		i = encodeVarintDatum(dAtA, i, uint64(m.Failed))
		i--
		dAtA[i] = 0x28
	}
	if m.Total != 0 {
		i = encodeVarintDatum(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x20
	}
	if m.Skipped != 0 {
		i = encodeVarintDatum(dAtA, i, uint64(m.Skipped))
		i--
		dAtA[i] = 0x18
	}
	if m.Processed != 0 {
		i = encodeVarintDatum(dAtA, i, uint64(m.Processed))
		i--
		dAtA[i] = 0x10
	}
	if m.ProcessStats != nil {
		{
			size, err := m.ProcessStats.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDatum(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PFSTask) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PFSTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PFSTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.AuthToken) > 0 {
		i -= len(m.AuthToken)
		copy(dAtA[i:], m.AuthToken)
		i = encodeVarintDatum(dAtA, i, uint64(len(m.AuthToken)))
		i--
		dAtA[i] = 0x22
	}
	if m.BaseIndex != 0 {
		i = encodeVarintDatum(dAtA, i, uint64(m.BaseIndex))
		i--
		dAtA[i] = 0x18
	}
	if m.PathRange != nil {
		{
			size, err := m.PathRange.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDatum(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Input != nil {
		{
			size, err := m.Input.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDatum(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PFSTaskResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PFSTaskResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PFSTaskResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.FileSetId) > 0 {
		i -= len(m.FileSetId)
		copy(dAtA[i:], m.FileSetId)
		i = encodeVarintDatum(dAtA, i, uint64(len(m.FileSetId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CrossTask) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CrossTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CrossTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.AuthToken) > 0 {
		i -= len(m.AuthToken)
		copy(dAtA[i:], m.AuthToken)
		i = encodeVarintDatum(dAtA, i, uint64(len(m.AuthToken)))
		i--
		dAtA[i] = 0x2a
	}
	if m.BaseIndex != 0 {
		i = encodeVarintDatum(dAtA, i, uint64(m.BaseIndex))
		i--
		dAtA[i] = 0x20
	}
	if m.BaseFileSetPathRange != nil {
		{
			size, err := m.BaseFileSetPathRange.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDatum(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.BaseFileSetIndex != 0 {
		i = encodeVarintDatum(dAtA, i, uint64(m.BaseFileSetIndex))
		i--
		dAtA[i] = 0x10
	}
	if len(m.FileSetIds) > 0 {
		for iNdEx := len(m.FileSetIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.FileSetIds[iNdEx])
			copy(dAtA[i:], m.FileSetIds[iNdEx])
			i = encodeVarintDatum(dAtA, i, uint64(len(m.FileSetIds[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *CrossTaskResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CrossTaskResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CrossTaskResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.FileSetId) > 0 {
		i -= len(m.FileSetId)
		copy(dAtA[i:], m.FileSetId)
		i = encodeVarintDatum(dAtA, i, uint64(len(m.FileSetId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *KeyTask) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.AuthToken) > 0 {
		i -= len(m.AuthToken)
		copy(dAtA[i:], m.AuthToken)
		i = encodeVarintDatum(dAtA, i, uint64(len(m.AuthToken)))
		i--
		dAtA[i] = 0x22
	}
	if m.Type != 0 {
		i = encodeVarintDatum(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x18
	}
	if m.PathRange != nil {
		{
			size, err := m.PathRange.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDatum(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.FileSetId) > 0 {
		i -= len(m.FileSetId)
		copy(dAtA[i:], m.FileSetId)
		i = encodeVarintDatum(dAtA, i, uint64(len(m.FileSetId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *KeyTaskResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyTaskResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyTaskResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.FileSetId) > 0 {
		i -= len(m.FileSetId)
		copy(dAtA[i:], m.FileSetId)
		i = encodeVarintDatum(dAtA, i, uint64(len(m.FileSetId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MergeTask) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MergeTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MergeTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.AuthToken) > 0 {
		i -= len(m.AuthToken)
		copy(dAtA[i:], m.AuthToken)
		i = encodeVarintDatum(dAtA, i, uint64(len(m.AuthToken)))
		i--
		dAtA[i] = 0x22
	}
	if m.Type != 0 {
		i = encodeVarintDatum(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x18
	}
	if m.PathRange != nil {
		{
			size, err := m.PathRange.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDatum(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.FileSetIds) > 0 {
		for iNdEx := len(m.FileSetIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.FileSetIds[iNdEx])
			copy(dAtA[i:], m.FileSetIds[iNdEx])
			i = encodeVarintDatum(dAtA, i, uint64(len(m.FileSetIds[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MergeTaskResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MergeTaskResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MergeTaskResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.FileSetId) > 0 {
		i -= len(m.FileSetId)
		copy(dAtA[i:], m.FileSetId)
		i = encodeVarintDatum(dAtA, i, uint64(len(m.FileSetId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ComposeTask) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ComposeTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ComposeTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.AuthToken) > 0 {
		i -= len(m.AuthToken)
		copy(dAtA[i:], m.AuthToken)
		i = encodeVarintDatum(dAtA, i, uint64(len(m.AuthToken)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.FileSetIds) > 0 {
		for iNdEx := len(m.FileSetIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.FileSetIds[iNdEx])
			copy(dAtA[i:], m.FileSetIds[iNdEx])
			i = encodeVarintDatum(dAtA, i, uint64(len(m.FileSetIds[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ComposeTaskResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ComposeTaskResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ComposeTaskResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.FileSetId) > 0 {
		i -= len(m.FileSetId)
		copy(dAtA[i:], m.FileSetId)
		i = encodeVarintDatum(dAtA, i, uint64(len(m.FileSetId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SetSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SetSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.SizeBytes != 0 {
		i = encodeVarintDatum(dAtA, i, uint64(m.SizeBytes))
		i--
		dAtA[i] = 0x10
	}
	if m.Number != 0 {
		i = encodeVarintDatum(dAtA, i, uint64(m.Number))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintDatum(dAtA []byte, offset int, v uint64) int {
	offset -= sovDatum(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Meta) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Job != nil {
		l = m.Job.Size()
		n += 1 + l + sovDatum(uint64(l))
	}
	if len(m.Inputs) > 0 {
		for _, e := range m.Inputs {
			l = e.Size()
			n += 1 + l + sovDatum(uint64(l))
		}
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.State != 0 {
		n += 1 + sovDatum(uint64(m.State))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.Stats != nil {
		l = m.Stats.Size()
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovDatum(uint64(m.Index))
	}
	l = len(m.ImageId)
	if l > 0 {
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Stats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProcessStats != nil {
		l = m.ProcessStats.Size()
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.Processed != 0 {
		n += 1 + sovDatum(uint64(m.Processed))
	}
	if m.Skipped != 0 {
		n += 1 + sovDatum(uint64(m.Skipped))
	}
	if m.Total != 0 {
		n += 1 + sovDatum(uint64(m.Total))
	}
	if m.Failed != 0 {
		n += 1 + sovDatum(uint64(m.Failed))
	}
	if m.Recovered != 0 {
		n += 1 + sovDatum(uint64(m.Recovered))
	}
	l = len(m.FailedId)
	if l > 0 {
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PFSTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Input != nil {
		l = m.Input.Size()
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.PathRange != nil {
		l = m.PathRange.Size()
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.BaseIndex != 0 {
		n += 1 + sovDatum(uint64(m.BaseIndex))
	}
	l = len(m.AuthToken)
	if l > 0 {
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PFSTaskResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FileSetId)
	if l > 0 {
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CrossTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.FileSetIds) > 0 {
		for _, s := range m.FileSetIds {
			l = len(s)
			n += 1 + l + sovDatum(uint64(l))
		}
	}
	if m.BaseFileSetIndex != 0 {
		n += 1 + sovDatum(uint64(m.BaseFileSetIndex))
	}
	if m.BaseFileSetPathRange != nil {
		l = m.BaseFileSetPathRange.Size()
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.BaseIndex != 0 {
		n += 1 + sovDatum(uint64(m.BaseIndex))
	}
	l = len(m.AuthToken)
	if l > 0 {
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CrossTaskResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FileSetId)
	if l > 0 {
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *KeyTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FileSetId)
	if l > 0 {
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.PathRange != nil {
		l = m.PathRange.Size()
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovDatum(uint64(m.Type))
	}
	l = len(m.AuthToken)
	if l > 0 {
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *KeyTaskResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FileSetId)
	if l > 0 {
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *MergeTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.FileSetIds) > 0 {
		for _, s := range m.FileSetIds {
			l = len(s)
			n += 1 + l + sovDatum(uint64(l))
		}
	}
	if m.PathRange != nil {
		l = m.PathRange.Size()
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovDatum(uint64(m.Type))
	}
	l = len(m.AuthToken)
	if l > 0 {
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *MergeTaskResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FileSetId)
	if l > 0 {
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ComposeTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.FileSetIds) > 0 {
		for _, s := range m.FileSetIds {
			l = len(s)
			n += 1 + l + sovDatum(uint64(l))
		}
	}
	l = len(m.AuthToken)
	if l > 0 {
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ComposeTaskResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FileSetId)
	if l > 0 {
		n += 1 + l + sovDatum(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SetSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Number != 0 {
		n += 1 + sovDatum(uint64(m.Number))
	}
	if m.SizeBytes != 0 {
		n += 1 + sovDatum(uint64(m.SizeBytes))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovDatum(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDatum(x uint64) (n int) {
	return sovDatum(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Meta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Meta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Meta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Job", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Job == nil {
				m.Job = &pps.Job{}
			}
			if err := m.Job.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inputs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inputs = append(m.Inputs, &common.Input{})
			if err := m.Inputs[len(m.Inputs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= State(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Stats == nil {
				m.Stats = &pps.ProcessStats{}
			}
			if err := m.Stats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImageId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ImageId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDatum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Stats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Stats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Stats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessStats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProcessStats == nil {
				m.ProcessStats = &pps.ProcessStats{}
			}
			if err := m.ProcessStats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Processed", wireType)
			}
			m.Processed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Processed |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skipped", wireType)
			}
			m.Skipped = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Skipped |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Failed", wireType)
			}
			m.Failed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Failed |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recovered", wireType)
			}
			m.Recovered = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Recovered |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FailedId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FailedId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDatum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PFSTask) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PFSTask: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PFSTask: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Input", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Input == nil {
				m.Input = &pps.PFSInput{}
			}
			if err := m.Input.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PathRange", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PathRange == nil {
				m.PathRange = &pfs.PathRange{}
			}
			if err := m.PathRange.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseIndex", wireType)
			}
			m.BaseIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseIndex |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDatum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PFSTaskResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PFSTaskResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PFSTaskResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileSetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileSetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDatum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CrossTask) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CrossTask: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CrossTask: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileSetIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileSetIds = append(m.FileSetIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFileSetIndex", wireType)
			}
			m.BaseFileSetIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseFileSetIndex |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFileSetPathRange", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BaseFileSetPathRange == nil {
				m.BaseFileSetPathRange = &pfs.PathRange{}
			}
			if err := m.BaseFileSetPathRange.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseIndex", wireType)
			}
			m.BaseIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseIndex |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDatum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CrossTaskResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CrossTaskResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CrossTaskResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileSetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileSetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDatum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KeyTask) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeyTask: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeyTask: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileSetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileSetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PathRange", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PathRange == nil {
				m.PathRange = &pfs.PathRange{}
			}
			if err := m.PathRange.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= KeyTask_Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDatum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KeyTaskResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeyTaskResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeyTaskResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileSetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileSetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDatum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MergeTask) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MergeTask: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MergeTask: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileSetIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileSetIds = append(m.FileSetIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PathRange", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PathRange == nil {
				m.PathRange = &pfs.PathRange{}
			}
			if err := m.PathRange.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= MergeTask_Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDatum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MergeTaskResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MergeTaskResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MergeTaskResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileSetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileSetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDatum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ComposeTask) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ComposeTask: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ComposeTask: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileSetIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileSetIds = append(m.FileSetIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDatum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ComposeTaskResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ComposeTaskResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ComposeTaskResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileSetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatum
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDatum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileSetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDatum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Number", wireType)
			}
			m.Number = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Number |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SizeBytes", wireType)
			}
			m.SizeBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SizeBytes |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDatum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDatum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDatum(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDatum
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDatum
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDatum
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDatum
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDatum
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDatum        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDatum          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDatum = fmt.Errorf("proto: unexpected end of group")
)
