FROM gcr.io/kubeflow-ci/tf-mnist-with-summaries:1.0

RUN pip install Minio
ADD tf_job_s3_gateway_minio.py /var/tf_mnist/tf_job_s3_gateway_minio.py
ADD testdata /testdata
ENTRYPOINT ["python", "/var/tf_mnist/tf_job_s3_gateway_minio.py"]




