#!/bin/sh

set -x

tar xf /dev/stdin
protoeasy --go --go-modifier plugins=<BS>grpc --go-import-path github.com/pachyderm/pachyderm/src src >/dev/null
protofix fix src >/dev/null
find src -regex ".*\.go" | xargs tar cf -
