#!/bin/sh
go build
rm -rf static
mkdir -p static/1Node
mkdir -p static/3Node
mkdir -p static/24Node
mkdir -p static/dev
./deploy -shards=1 && mv *.service static/1Node
./deploy -shards=3 && mv *.service static/3Node
./deploy -shards=24 && mv *.service static/24Node
./deploy -shards=12 -container="\`etcdctl get /pfs/registry\`/pfs" && mv *.service static/dev
cd static
tar -zcvf 1Node.tar.gz 1Node
tar -zcvf 3Node.tar.gz 3Node
tar -zcvf 24Node.tar.gz 24Node
cd ..
