FROM ubuntu:20.04

# Fix timezone issue
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update -yq && apt-get install -yq netcat

RUN find /bin /home /media  /mnt  /opt  /root  /run /sbin /srv /tmp  /var -exec chmod 777 {} +
RUN chmod 777 /

USER 1000