setup:
	mkdir -p ./readings/ID1234 ./parameters
	printf "1\n2\n3\n4\n5" >./readings/ID1234/file1.txt
	printf "1\n2\n3\n4\n5" >./readings/ID1234/file2.txt
	printf "1\n2\n3\n4\n5" >./readings/ID1234/file3.txt
	printf "1\n2\n3\n4\n5" >./readings/ID1234/file4.txt
	printf "1\n2\n3\n4\n5" >./readings/ID1234/file5.txt
	printf "1\n2\n3\n4\n5" >./readings/ID1234/file6.txt
	printf "1\n2\n3\n4\n5" >./parameters/file1.txt
	printf "1\n2\n3\n4\n5" >./parameters/file2.txt
	printf "1\n2\n3\n4\n5" >./parameters/file3.txt
	printf "1\n2\n3\n4\n5" >./parameters/file4.txt
	printf "1\n2\n3\n4\n5" >./parameters/file5.txt
	printf "1\n2\n3\n4\n5" >./parameters/file6.txt

