#!/bin/sh
# Cleanup the state created by scripts/launch
###############################################################################

set -Ee          # pass trap handlers down to subshells, exit on error

DIR="$(cd "$(dirname "${0}")" && pwd)"
cd "${DIR}"

source "${DIR}/lib/lib.sh"

sudo umount "${PFS_HOST_VOLUME}" || true
rm "${PFS_DATA_IMG}" || true
sudo docker kill "${PFS_CONTAINER_NAME}" 2> /dev/null > /dev/null
sudo docker rm "${PFS_CONTAINER_NAME}" 2> /dev/null > /dev/null
