#!/bin/sh
# Wraps the pfs container to make the deploy tool feel like a commandline tool.

mkdir -p /home/core/pfs
sudo docker run \
    --privileged=true \
    -v /:/host:ro \
    -v /home/core:/host/home/core \
    -v /var/run/fleet.sock:/host/var/run/fleet.sock \
    -i pachyderm/pfs \
    /go/bin/deploy $@ && fleetctl start /home/core/pfs/*.service
