#!/bin/sh
# Launch pfs in single node mode, using the current source tree to build the image.
###############################################################################

set -Ee          # pass trap handlers down to subshells, exit on error

DIR="$(cd "$(dirname "${0}")" && pwd)"
cd "${DIR}"

source "${DIR}/lib/lib.sh"

log_command "${DIR}/build"
log_command "${DIR}/launch" $@
