#!/bin/sh
# Launch pfs in single node mode, using the current source tree to build the image.
###############################################################################

set -Ee          # pass trap handlers down to subshells, exit on error

DIR="$(cd "$(dirname "${0}")" && pwd)"
cd "${DIR}"

. "${DIR}/lib/lib.sh"

export PFS_IMAGE=pachyderm/pfsdev
log_command "${DIR}/build"
log_command "${DIR}/launch" $@
