#!/bin/sh
# Launch pfs tests in single node mode.
###############################################################################

set -Ee          # pass trap handlers down to subshells, exit on error

DIR="$(cd "$(dirname "${0}")" && pwd)"
cd "${DIR}"

. "${DIR}/lib/lib.sh"

PFS_DAEMONIZE= "${DIR}/dev-launch" sh /go/src/github.com/pachyderm/pfs/scripts/run_tests_from_within_container
