#!/bin/sh
# Launch pfs tests in single node mode.
###############################################################################

set -Ee          # pass trap handlers down to subshells, exit on error

DIR="$(cd "$(dirname "${0}")" && pwd)"
cd "${DIR}"

source "${DIR}/lib/lib.sh"

HELP="A script to launch pfs tests in single node mode.\nUsage: $0 [-p port] [-i image]"

"${DIR}/dev-launch" -f sh /go/src/github.com/pachyderm/pfs/scripts/run_tests_from_within_container
