#!/bin/sh
# Install a git repo on a pfs cluster.
###############################################################################
set -E          # pass trap handlers down to subshells
#set -x         # execution tracing debug messages

USAGE="Usage: $0 host"

# --- Options processing -------------------------------------------
if [ $# != 1 ] ; then
    echo $USAGE
    exit 1;
fi
CMD="$0"
CMD_DIR="$(cd "$(dirname "$CMD")" && pwd)"
HOST="$1"

REPO=$(basename `pwd`)
REMOTE="$HOST":/home/core/"$REPO".git

echo "Installing $REMOTE"

rm -rf /tmp/"$REPO".git
git clone --bare "$REPO" /tmp/"$REPO".git
scp -rqC /tmp/"$REPO".git core@"$REMOTE"
scp -rqC "$CMD_DIR"/post-receive core@"$REMOTE"/hooks/post-receive
git remote remove pachyderm
git remote add pachyderm git://"$HOST"/home/core/"$REPO".git

echo "Done."
