#!/bin/sh
# Install a git repo on a pfs cluster.
# Run this from the route of your pfs repo.
###############################################################################

set -Ee          # pass trap handlers down to subshells, exit on error

DIR="$(cd "$(dirname "${0}")" && pwd)"
cd "${DIR}"

source "${DIR}/lib/lib.sh"

USAGE="Usage: ${0} host"

if [ $# != 1 ] ; then
    echo "${USAGE}" >&2
    exit 1
fi
HOST="${1}"

REPO=$(basename "${PFS_REPO_DIR}")
REMOTE="$HOST":/home/core/"$REPO".git

echo "Installing $REMOTE"

rm -rf /tmp/"$REPO".git
git clone --bare . /tmp/"$REPO".git
scp -rqC /tmp/"$REPO".git core@"$REMOTE"
scp -rqC "${DIR}/post-receive" "core@${REMOTE}/hooks/post-receive"
git remote remove pachyderm
git remote add pachyderm git://"$HOST"/home/core/"$REPO".git

echo "Done."
