#!/bin/sh
REPOSITORY_BASENAME=$(basename "$PWD")
REPOSITORY_BASENAME=${REPOSITORY_BASENAME%.git}
if [ ! -d "/tmp/$REPOSITORY_BASENAME" ]; then
  git clone "$PWD" /tmp/"$REPOSITORY_BASENAME"
fi

export GIT_WORK_TREE="/tmp/$REPOSITORY_BASENAME"
git checkout -f

# Build the image
reg=$(etcdctl get /pfs/registry)
sudo docker build -t "$reg"/"$REPOSITORY_BASENAME" /tmp/"$REPOSITORY_BASENAME"/image
sudo docker push "$reg"/"$REPOSITORY_BASENAME"
curl -sS -XPOST "localhost/branch?branch=$REPOSITORY_BASENAME&commit=t0"
for j in /tmp/"$REPOSITORY_BASENAME"/job/*
do
    jobname=$(basename $j)
    echo "Create $jobname from $j"
    sed "s/{{REPO_IMAGE}}/\"$reg\/$REPOSITORY_BASENAME\"/g" $j | curl -sS -XPOST "localhost/job/$jobname?branch=$REPOSITORY_BASENAME" -T -
done
curl -sS -XPOST "localhost/commit?branch=$REPOSITORY_BASENAME&run"
