FROM registry.access.redhat.com/ubi8/ubi-minimal@sha256:2e4bbb2be6e7aff711ddc93f0b07e49c93d41e4c2ffc8ea75f804ad6fe25564e

LABEL name="console"
LABEL vendor="Pachyderm, Inc."
LABEL description="Pachyderm's official dashboard for enterprise Pachyderm users."
LABEL summary="Pachyderm's official dashboard for enterprise Pachyderm users."

WORKDIR /usr/src/app

# Install nodejs
RUN microdnf install tar xz
RUN curl -sLO https://nodejs.org/dist/v16.14.0/node-v16.14.0-linux-x64.tar.xz && \
  tar xf node-v16.14.0-linux-x64.tar.xz -C /usr/local
ENV PATH=/usr/local/node-v16.14.0-linux-x64/bin:${PATH}

ADD . .

RUN microdnf install pango giflib cmake cairo libjpeg-turbo libjpeg-turbo-devel

# update with new canvas versions
RUN npm install canvas@2.8.0

RUN make ci

RUN make build

RUN make prune-deps

# Fix npm vulnerabilities where possible, but don't introduce breaking changes
# in the build. Ignore non-zero exit codes as not all vulnerabilities can be
# addressed without introducing breaking changes (but any unaddressed
# vulnerabilities cause 'npm audit fix' to exit with a non-zero code).
RUN npm audit fix || true

# Update dependencies in the base images, in case any have vulnerability fixes
# (checked by Red Hat's image validator)
RUN microdnf install yum \
  && yum -y update \
  && yum clean all \
  && microdnf clean all

# Add dependency licenses
RUN mkdir /licenses \
  && echo "These licenses are distributed alongside the Pachyderm Console in accordance with our dependencies' terms. They were collected and copied here by the 'generate-license-file' NPM package." >/licenses/README.txt \
  && npm install generate-license-file -g \
  && generate-license-file --input package.json --output /licenses/third-party-licenses.txt --overwrite \
  && npm uninstall generate-license-file

CMD ["npm", "start", "--prefix", "./backend"]
EXPOSE 4000
