# Copyright 2016 The TensorFlow Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM gcr.io/kubeflow-ci/tf-mnist-with-summaries:1.0

RUN pip install Minio

ADD tf_job_s3_gateway.py /var/tf_mnist/tf_job_s3_gateway.py
ADD blah /blah
ENTRYPOINT ["python", "/var/tf_mnist/tf_job_s3_gateway.py"]




