#!/usr/local/bin/bash

# output manifest file
OUTPUT_MANIFEST=/pfs/out/tfjob_deployed.yaml

# command line arguments
echo "Parsing command line args"
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -f|--file)
    INPUT_MANIFEST="$2"
    shift # past argument
    shift # past value
    ;;
esac
done
set -- "${POSITIONAL[@]}" 

# proxy kubernetes API
echo "Starting k8s proxy"
kubectl proxy &
sleep 1

# pre-process the input manifest
echo "Pre-processing input manifest"
JOBNAME=$(./preprocess $INPUT_MANIFEST $OUTPUT_MANIFEST /pfs)

# launch TFJob
echo "Creating TFJob"
kubectl create -f $OUTPUT_MANIFEST --server=http://127.0.0.1:8001

# monitor the TFJob until it finishes
until [ "$( echo $(kubectl get -o json tfjobs $JOBNAME --server=http://127.0.0.1:8001) | jq '.status.state' 2>&1 )" == "\"Succeeded\"" ];
do
	echo "Waiting for TFJob to finish..."
        sleep 10
done 

# clean up
echo "Cleaning up TFJob"
kubectl delete tfjob $JOBNAME --server=http://127.0.0.1:8001
kill %1
